#include <LSM6DS3.h>
#include <Wire.h>

#include <TensorFlowLite.h>
#include <tensorflow/lite/micro/micro_error_reporter.h>
#include <tensorflow/lite/micro/micro_interpreter.h>
#include <tensorflow/lite/micro/micro_mutable_op_resolver.h>
#include <tensorflow/lite/schema/schema_generated.h>

#include "model.h"

#include <ArduinoBLE.h>    // 🛠 Core BLE library for radio control

// =====================
// BLE SETUP
// =====================

#define DEVICE_NAME "CIoT"
#define DEVICE_ID "a38deac2-1ab2-4d23-8ba4-e68399782297"
// 160 units * 0.625 ms = 100 milliseconds (advertises 10 times a second).
#define ADV_INTERVAL 1600 * 1

// =====================
// IMU SETUP
// =====================

LSM6DS3 myIMU(I2C_MODE, 0x6A);

// =====================
// MODEL PARAMETERS
// (must match the notebook exactly)
// =====================

// Notebook: x_train = (x_train - mean) / (std + 1e-8)
#define TRAIN_MEAN  -0.05578711f
#define TRAIN_STD   32.85033798f   

#define SAMPLING_DELAY  20          // ms  → 50 Hz
#define NUM_SAMPLES     120         // notebook: reshape(-1, 120, 6)
#define NUM_FEATURES    6           // aX aY aZ gX gY gZ
#define NUM_GESTURES    4           // notebook: num_classes = 4

// =====================
// INT8 QUANTIZATION PARAMETERS
// (read from the TFLite model at conversion time)
// =====================
#define INPUT_SCALE      0.076956f   
#define INPUT_ZERO_POINT 0      

// =====================
// TFLITE SETUP
// =====================

tflite::MicroErrorReporter tflErrorReporter;

// Ops used by the compressed student:
//   Conv1D  → AddConv2D (TFLite Micro maps Conv1D to Conv2D internally)
//   GlobalAveragePooling1D → AddMean
//   Dense   → AddFullyConnected
//   INT8 conversion wrappers → AddQuantize / AddDequantize
tflite::MicroMutableOpResolver<6> tflOpsResolver;

const tflite::Model*      tflModel       = nullptr;
tflite::MicroInterpreter* tflInterpreter = nullptr;
TfLiteTensor*             tflInputTensor = nullptr;
TfLiteTensor*             tflOutputTensor = nullptr;

// Increase if "AllocateTensors() failed" appears on Serial.
constexpr int tensorArenaSize = 10 * 1024;
byte tensorArena[tensorArenaSize] __attribute__((aligned(16)));

int samplesRead   = 0;
int lastPrediction = -1;

// =====================
// BLE HELPER
// =====================

void setGesture(uint8_t gesture) {
  uint8_t mfgData[3];
  mfgData[0] = 0x34;    // company ID LSB
  mfgData[1] = 0x12;    // company ID MSB
  mfgData[2] = gesture; // gesture value (0 = idle, 1-4 = detected class)
  BLE.setManufacturerData(mfgData, sizeof(mfgData));
}

// =====================
// SETUP
// =====================

void setup() {
  Serial.begin(9600);
  while (!Serial);

  // --- BLE ---
  if (!BLE.begin()) {
    Serial.println("Starting BLE failed!");
    while (1);
  }

  // --- IMU ---
  if (myIMU.begin() != 0) {
    Serial.println("IMU Error");
    while (1);
  }

  // --- TFLite model ---
  // The header generated by the notebook declares:
  //   extern const unsigned char mnist_model[];
  //   extern const unsigned int  mnist_model_len;
  // Make sure model.h uses those exact names.
  tflModel = tflite::GetModel(model);

  if (tflModel->version() != TFLITE_SCHEMA_VERSION) {
    Serial.println("Model schema mismatch!");
    while (1);
  }

  // Register only the ops that the compressed student actually uses.
  // Conv1D is lowered to Conv2D by TFLite; GlobalAveragePooling1D → Mean.
  tflOpsResolver.AddConv2D();
  tflOpsResolver.AddMean();             // GlobalAveragePooling1D
  tflOpsResolver.AddFullyConnected();
  tflOpsResolver.AddQuantize();
  tflOpsResolver.AddDequantize();
  tflOpsResolver.AddReshape();

  tflInterpreter = new tflite::MicroInterpreter(
    tflModel,
    tflOpsResolver,
    tensorArena,
    tensorArenaSize,
    &tflErrorReporter
  );

  if (tflInterpreter->AllocateTensors() != kTfLiteOk) {
    Serial.println("AllocateTensors() failed — increase tensorArenaSize");
    while (1);
  }

  tflInputTensor  = tflInterpreter->input(0);
  tflOutputTensor = tflInterpreter->output(0);

  // --- BLE advertising ---
  BLE.setLocalName(DEVICE_NAME);
  BLE.setAdvertisingInterval(ADV_INTERVAL);
  BLE.setAdvertisedServiceUuid(DEVICE_ID);
  setGesture(0);   // idle / no gesture
  BLE.advertise();

  Serial.println("Device OK");
}

// =====================
// LOOP
// =====================

void loop() {

  // -------------------------------------------------------
  // 1. COLLECT 120 SAMPLES  (120 × 6 = 720 float values)
  // -------------------------------------------------------
  while (samplesRead < NUM_SAMPLES) {

    float raw[NUM_FEATURES] = {
      myIMU.readFloatAccelX(),
      myIMU.readFloatAccelY(),
      myIMU.readFloatAccelZ(),
      myIMU.readFloatGyroX(),
      myIMU.readFloatGyroY(),
      myIMU.readFloatGyroZ()
    };

    // ---------------------------------------------------
    // NORMALISATION — matches the notebook's z-score step:
    //   x_train = (x_train - mean) / (std + 1e-8)
    // then quantise to INT8 for the fully-integer model:
    //   img_int8 = (float_value / input_scale + input_zero_point)
    // ---------------------------------------------------
    int baseIdx = samplesRead * NUM_FEATURES;
    for (int f = 0; f < NUM_FEATURES; f++) {
      float normalised = (raw[f] - TRAIN_MEAN) / (TRAIN_STD + 1e-8f);
      int8_t quantised = (int8_t)(normalised / INPUT_SCALE + INPUT_ZERO_POINT);
      tflInputTensor->data.int8[baseIdx + f] = quantised;
    }

    samplesRead++;
    delay(SAMPLING_DELAY);
  }

  // -------------------------------------------------------
  // 2. RUN INFERENCE
  // -------------------------------------------------------
  if (tflInterpreter->Invoke() != kTfLiteOk) {
    Serial.println("Inference failed!");
    samplesRead = 0;
    return;
  }

  // -------------------------------------------------------
  // 3. GET RESULTS  (INT8 logits — higher = more likely)
  // -------------------------------------------------------
  int   bestIndex = 0;
  int8_t bestScore = tflOutputTensor->data.int8[0];

  for (int i = 1; i < NUM_GESTURES; i++) {
    int8_t score = tflOutputTensor->data.int8[i];
    if (score > bestScore) {
      bestScore = score;
      bestIndex = i;
    }
  }

  Serial.print("Best gesture (1-based): ");
  Serial.println(bestIndex + 1);

  // -------------------------------------------------------
  // 4. ADVERTISE RESULT  (only when the prediction changes)
  //    BLE payload: 1-based gesture index (0 = idle)
  // -------------------------------------------------------
  if (bestIndex != lastPrediction) {
    BLE.stopAdvertise();
    setGesture((uint8_t)(bestIndex + 1));  // 1-4 → matches original convention
    BLE.advertise();

    Serial.print("Updated BLE gesture: ");
    Serial.println(bestIndex + 1);

    lastPrediction = bestIndex;
  }

  // -------------------------------------------------------
  // 5. RESET
  // -------------------------------------------------------
  samplesRead = 0;
}
